export enum SwapStatus {
  REQUESTED = 'REQUESTED',
  VALIDATING = 'VALIDATING',
  OLD_SIM_DEACTIVATING = 'OLD_SIM_DEACTIVATING',
  NEW_SIM_ACTIVATING = 'NEW_SIM_ACTIVATING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
